version: '3.3'

services:
  
  error-pages:
    image: tarampampam/error-pages:2.2.0
    container_name: http_error_pages
    hostname: web01
    
    environment:
      - TEMPLATE_NAME=ghost #Set Custom error page template https://github.com/tarampampam/error-pages
      - TZ=America/New_York #Set host Timezone
    labels:
      #Enable monitoring with Traefik Proxy
      - traefik.enable=true
      - traefik.docker.network=http_error_pages_default # Configure Traefik to autojoin stack network
      #Configure traefilk Proxy Route 
      # use as "fallback" for any non-registered services (with priority below normal)
      - traefik.http.routers.error-pages-router.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.error-pages-router.priority=10
      - traefik.http.routers.error-pages-router.tls=true
      - traefik.http.routers.error-pages-router.entrypoints=websecure
      - traefik.http.routers.error-pages-router.middlewares=error-pages-middleware@docker # Enable Custom Errorpages for Router
      #Configure host services in Traefik Proxy   
      - traefik.http.services.error-pages-service.loadbalancer.server.port=8080
      #Configure traefik middleware to handle error http error response
      - traefik.http.middlewares.error-pages-middleware.errors.status=400-599
      - traefik.http.middlewares.error-pages-middleware.errors.service=error-pages-service@docker
      - traefik.http.middlewares.error-pages-middleware.errors.query=/{status}.html

    restart: unless-stopped