version: '3.3'

volumes:
  nessus_data:
    driver: local

services:
  nessus:
    image: tenableofficial/nessus
    container_name: nessus-pro
    hostname: nessus

    environment:
      - TZ=America/New_York #Set host Timezone
      - ACTIVATION_CODE=Nessus_License_Key_Here #Nessus License key 
      #- LINKING_KEY=Link_Key_Here #link key for managed nessus scaner 
      #- NAME=Scanner_name #Define name as shown in Nessus manager
      #- MANAGER_HOST=IP_of_manager #Nessus Manager address
      #- MANAGER_PORT=Port #Nessus Manager Port 
      - AUTO_UPDATE=all #valid options all,plugins,no 
      - USERNAME=Username_for_initial_setup #Needed for initial build
      - PASSWORD=Password_for_initial_setup #Needed for initial build change password on first login
    
    volumes:
      - nessus_data:/opt/nessus/var/nessus #Persist plugin and db storage in docker volume 

    labels:
      #Enable monitoring with Traefik Proxy
      - traefik.enable=true
      - traefik.docker.network=nessus_default #Configure Traefik to autojoin stack network
      #Configure traefilk Proxy Route
      - traefik.http.routers.nessus.entrypoints=websecure
      - traefik.http.routers.nessus.rule=Host(`nessus.tools.local`)
      - traefik.http.routers.nessus.tls=true
      - traefik.http.routers.nessus.service=nessus
      - traefik.http.routers.nessus.middlewares=error-pages-middleware@docker #Enable Custom Errorpages for Router
      #Configure host services in Traefik Proxy 
      - traefik.http.services.nessus.loadbalancer.server.port=8834
       #Disable auto image updates with Watchtower 
      - com.centurylinklabs.watchtower.enable=false

    restart: unless-stopped